language: python
type: push
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app bash -c "python manage.py wait_for_db && python manage.py test && flake8"